config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

      post "like", to: 'products#asign_like'
      resources :products, only: [:index]
      resources :order, only: [:index, :show, :update, :destroy]
      resources :order_lines, only: [:create]

      post 'password/forgot', to: 'password#forgot'
      post 'password/recover', to: 'password#recover'
      put 'password/update', to: 'password#update_password'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  concern :commentable do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:index, :update, :destroy]
  
  namespace :admin do 
    resources :users
    resources :product, concerns: :commentable
    resources :orders, only: [:index, :show], concerns: :commentable
    get 'product_log', :to => 'productslogs#index'
  end
  
  get "/like", to: 'product#asign_like'
  get "/cart", to: 'cart#index'
  
  resources :orders, only: [:index, :show, :update], concerns: :commentable
  resources :order_lines, only: [:create, :destroy]
  resources :product, except: [:destroy, :create, :new], concerns: :commentable
  resources :profiles, concerns: :commentable
  resources :customers, only: [:index, :new, :create]
  resources :charges
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_lines
  has_many :products, through: :order_lines
  has_many :comments, as: :commentable

  enum status: { abandoned: "abandoned", canceled: "canceled", open: "open", complete: "complete" }

  validates :status, presence: true

  before_update :update_stock
  before_update :calc_total

  def total

    order_lines.inject(0) { |sum, orln| sum += orln.total}
  end

  def total_to_cents
    total * 100
  end

  private

  def update_stock
    # It decreases the stock of all products in the order which has been completed
    return unless status == 'complete'
    
    order_lines.each do |orln|
      stock = orln.product.stock - orln.quantity
      orln.product.update!(stock: stock)
    end
  end

  def calc_total
    self.total = order_lines.inject(0) { |sum, orln| sum += orln.total}
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all
    authorize [:admin, Order]
  end

  def show
    authorize [:admin, Order]
    @order = OrderQuery.new.get(params[:id])
    setup_next_comment('Order', @order)
  end
end

app/controllers/api/v1/order_controller.rb
module Api
  module V1
    class OrderController < ApplicationController
    
      def index
        @orders = Order.where(user_id: current_user.id)  
      end
    
      def show
        @order = OrderAsigner.new(current_user, params["order"]).call
      end

      def update
        @order = Order.find(params[:order_id])
        stripe_card_id = CreditCardService.new(current_user.id, params[:stripeToken]).create_credit_card

        unless @order.total > 0
          render :json => {error: 'Order\'s total can\'t be 0'}, status: :bad_request
          return
        end

        Stripe::Charge.create(
          customer: current_user.stripe_id,
          source:   stripe_card_id,
          amount:   @order.total_to_cents.to_i,
          currency: 'usd'
        )
  
        @order.update!(status: 'complete', completed_at: Time.now.getutc)
        head :no_content

      rescue Stripe::CardError => e
        render :json => { :error => "#{e.message}"}
      end  

      def destroy
        @order = OrderAsigner.new(current_user).call
        @order.update!(status: 'canceled')
        head :no_content
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [ :update ]
  before_action :authenticate_user!

  def index
    @orders = OrderQuery.new.order_from_user(current_user.id)
  end

  def show
    @order = OrderQuery.new.get(params[:id])
    setup_next_comment('Order', @order)
  end

  private

  def set_order
    @order = OrderQuery.new.get(session[:order_id])
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<table>
  <tr> 
    <th>Id</th>
     <th>Customer id</th>
    <th>Completed at</th> 
    <th>Total</th>
    <th>Status</th>
    <th>
    </th>
  </tr>
  <% @orders.each do |order| %>
  <tr>
    <td>
      <%= order.id %>
    </td>
    <td>
      <%= order.user_id %>
    </td>
    <td>
      <%= order.completed_at %>
    </td>
    <td>
      $<%= order.total %>
    </td>
    <td>
      <%= order.status %>
    </td>
    <td>
      <%= link_to "Details",admin_order_path(order.id) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/orders/show.html.erb
<h2> Order Number: <%= @order.id %> </h2>
<table>
  <tr> 
    <th>Product</th> 
    <th>Price</th> 
    <th>Quantity</th>
    <th>Total</th>
  </tr>
<% @order.order_lines.each do |orln| %>
  <tr>
    <td>
      <%= orln.product_name %>
    </td>
    <td>
      $<%= orln.price %>
    </td>
    <td>
      <%= orln.quantity %>
    </td>
    <td>
      <%= orln.total %>
    </td>
  </tr>
<% end %>
</table>
<div>
  <%= render partial: "shared/new_comment", locals: { comment: @comment, commentable: @commentable, type: @type, current_user: current_user, comments: @comments } %>
</div>
<%= link_to "Regresar", admin_orders_path %>