config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

      post "like", to: 'products#asign_like'
      resources :products, only: [:index]
      resources :order, only: [:index, :show, :update, :destroy]
      resources :order_lines, only: [:create]

      post 'password/forgot', to: 'password#forgot'
      post 'password/recover', to: 'password#recover'
      put 'password/update', to: 'password#update_password'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  concern :commentable do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:index, :update, :destroy]
  
  namespace :admin do 
    resources :users
    resources :product, concerns: :commentable
    resources :orders, only: [:index, :show], concerns: :commentable
    get 'product_log', :to => 'productslogs#index'
  end
  
  get "/like", to: 'product#asign_like'
  get "/cart", to: 'cart#index'
  
  resources :orders, only: [:index, :show, :update], concerns: :commentable
  resources :order_lines, only: [:create, :destroy]
  resources :product, except: [:destroy, :create, :new], concerns: :commentable
  resources :profiles, concerns: :commentable
  resources :customers, only: [:index, :new, :create]
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  delegate :email, to: :user, prefix: true
  delegate :user, to: :commentable, prefix: true 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product

  enum kind: { dislike: "dislike", like: "like" }

  validates :kind, presence: true

  scope :user_like, ->(user, product) { where('user_id = ? AND product_id = ?', user, product) }

  before_update :take_like
  after_save :calc_like

  private

  # when updating it removes the corresponding kind of like
  def take_like
    if kind_was == "like"
      product.like_count -= 1
    else
      product.dislike_count -= 1
    end
  end

  # when creating or saving a like it updates the counter in the appropriate product
  def calc_like
    if kind == "like"
      product.like_count += 1
    else
      product.dislike_count += 1
    end
    product.save!
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_lines
  has_many :products, through: :order_lines
  has_many :comments, as: :commentable

  enum status: { abandoned: "abandoned", canceled: "canceled", open: "open", complete: "complete" }

  validates :status, presence: true

  before_update :update_stock
  before_update :calc_total

  def total

    order_lines.inject(0) { |sum, orln| sum += orln.total}
  end

  def total_to_cents
    total * 100
  end

  private

  def update_stock
    # It decreases the stock of all products in the order which has been completed
    return unless status == 'complete'
    
    order_lines.each do |orln|
      stock = orln.product.stock - orln.quantity
      orln.product.update!(stock: stock)
    end
  end

  def calc_total
    self.total = order_lines.inject(0) { |sum, orln| sum += orln.total}
  end
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :order
  belongs_to :product

  delegate :name, to: :product, prefix: true

  validates :quantity, :price, :order_id, :product_id, presence: true
  validates :quantity, numericality: { greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }

  validate :check_stock
  before_save :calc_total

  private

  def check_stock
    product = Product.find(product_id)

    if product.stock < quantity
      errors.add(:quantity, "Not enough product in stock")
    end
  end

  def calc_total
    self.total = price*quantity
  end
end

app/models/product.rb
# frozen_string_literal: true

# Module of table products
class Product < ApplicationRecord
  has_many :order_lines
  has_many :orders, through: :order_lines
  has_many :product_prices_log
  has_many :product_tags
  has_many :tags, through: :product_tags
  has_many :likes
  has_many :comments, as: :commentable
  has_one_attached :picture

  validates :price, :stock, :description, :name, :sku, presence: true
  validates :sku, uniqueness: true
  validates :price, numericality: { greater_than_or_equal_to: 10 }
  validates :stock, numericality: { greater_than_or_equal_to: 1 }, on: :create
  validates :stock, numericality: { greater_than_or_equal_to: 0 }, on: :update

  scope :sclikes, -> { order(like_count: :DESC) }
  scope :scdislikes, -> { order(dislike_count: :DESC) }
  scope :scnames, -> { order(:name) }

  after_update :monitor_stock

  private

  def monitor_stock
    return unless stock < 4

    return unless previous_changes['stock'].present?

    MailerFromMonitorStock.perform_async(id) if like_count > 0
  end
end

app/models/product_prices_log.rb
class ProductPricesLog < ApplicationRecord
  belongs_to :product
  belongs_to :user, foreign_key: :admin_id

  validates :price_before, :price_after, presence: true
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :tag
  belongs_to :product

  validates :tag_id, uniqueness: { scope: :product_id, case_sensitive: true}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  
  def is_able_to_be_commented?(current_user)
    user != current_user
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product_tags
  has_many :products, through: :product_tags

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_one :profile
  has_many :product_prices_log, as: :admin
  has_many :likes
  has_many :comments

  after_create :asign_profile
  before_create :assign_customer_id

  def asign_profile
    create_profile    
  end

  def assign_customer_id
    customer = Stripe::Customer.create(email: email)
    self.stripe_id = customer.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_comment.html.erb
<div class="ui comments">
  <h3 class="ui dividing header">Comments</h3>
  <% comments.each do |cm| %>
    <% if cm.id != nil %>
    <div class="comment">
      <div class="content">
        <a class="author"><%= cm.user_email %> 
          <%cm.rating.times do |r|%>
            <i class="star icon"></i>
          <%end%>
        </a>
        <div class="metadata">
          <span class="date"><%= cm.created_at %></span>
          <% if (current_user && current_user.admin > 0) || cm.user_id == current_user.id %>
            <span><%= "Pending of aproval" unless cm.publish%></span>
          <%end%>
        </div>
        <div class="text">
          Said:
           <%= cm.body %>
        </div>
      </div>
    </div>
    <%end%>
  <%end%>
</div>

app/views/shared/_flash_message.html.erb
<% if notice %>
  <p class="alert alert-success ui floating message teal"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger ui floating message red"><%= alert %></p>
<% end %>
<% if flash[:error] %>
  <div class="ui floating yellow message">
    <p>Number of errors: <%=flash[:error].size%></p>
    <% flash[:error].each do |k, e| %>   
      <p><%=k%>:<%=e%></p>
    <%end%>
  </div>
<%end%>
<% if flash[:success] %>
  <div class="ui floating green message"><%= flash[:success]%></div>
<%end%>

app/views/shared/_header.html.erb
<div class="ui secondary pointing menu">
  <% if current_user %>
      <%= link_to current_user.email, root_path, :class=>"active item" %>
    <% if current_user.admin == 2 %>
      <%= link_to "Add user", new_admin_user_path, :class=>"item"%>
      <%= link_to "Add product", new_admin_product_path, :class=>"item" %>
      <%= link_to "Pending Comments", comments_path, :class=>"item"%>
      <%= link_to "Product Log", admin_product_log_path, :class=>"item" %>
      <%= link_to "Orders Log", admin_orders_path, :class=>"item" %>
    <% else %>
      <%if current_user.admin == 1%>
        <%= link_to "Add user", new_customer_path, :class=>"item"%>
        <%= link_to "Pending Comments", comments_path, :class=>"item"%>
      <%end%>
      <%= link_to cart_path, :class => "ui labeled icon button", :class=>"item" do%>
        <i class="shopping cart icon"></i>Cart
      <%end%>
      <%= link_to "My Orders", orders_path, :class=>"item" %>
      <%if current_user.profile.present?%>
        <%= link_to "My Profile", profile_path(current_user.profile.id), :class=>"item" %>
      <%end%>
    <% end %>
    <div class="right menu">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class=>"ui item" %>
    </div>
  <% else %>
    <%= link_to root_path, :class => "ui labeled icon button", :class=>"item" do%>
      <i class="cubes icon"></i>Home
    <%end%>
    <%= link_to cart_path, :class => "ui labeled icon button", :class=>"item" do%>
      <i class="shopping cart icon"></i>Cart
    <%end%>
    <div class="right menu">
      <%= link_to new_user_session_path, :class => "ui labeled icon button", :class=>"ui item" do%>
        <i class="user circle icon"></i>Sign In
      <%end%>
    </div>
  <% end %>  
</div>

app/views/shared/_link_back.html.erb
<br>
<div class="ui vertical labeled icon buttons">
  <%= link_to root_path :class => "ui button" do %>
    <i class="reply icon"></i>Regresar
  <%end%>
</div>

app/views/shared/_new_comment.html.erb
<% if current_user %>
  <% if commentable.is_a?(Product) || (commentable.is_a?(Order) && commentable.status != 'complete') || (commentable.is_a?(Profile) && commentable.is_able_to_be_commented?(current_user)) %>
      <%= form_for ([commentable, comment]), html: { autocomplete: "off" }, remote: true, :class=>"ui reply form" do |f| %>
        <%= f.hidden_field :rating, :value => 0 %>
        <%= f.hidden_field :type, :value => type %><br>
        <div id="rate" class="ui star rating" data-rating="0"%> ></div><br>
        <%= f.text_area :body %><br>
        <% label = commentable.is_a?(Profile) ? "Submit Review" : "Submit Comment" %>
        <%= f.submit label, :class=>"ui blue labeled submit icon button" do %>
          <i class="icon edit"></i>
        <%end%>
      <% end %>
  <%end%>
<%end%>
<div id="comments">
  <br>
  <%= render partial: "shared/comment", locals: {:comments => @comments} %>
</div>