config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :authorizations, :applications, :authorized_applications
  end
  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

      post "like", to: 'products#asign_like'
      resources :products, only: [:index]
      resources :order, only: [:index, :show, :update, :destroy]
      resources :order_lines, only: [:create]

      post 'password/forgot', to: 'password#forgot'
      post 'password/recover', to: 'password#recover'
      put 'password/update', to: 'password#update_password'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  concern :commentable do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:index, :update, :destroy]
  
  namespace :admin do 
    resources :users
    resources :product, concerns: :commentable
    resources :orders, only: [:index, :show], concerns: :commentable
    get 'product_log', :to => 'productslogs#index'
  end
  
  get "/like", to: 'product#asign_like'
  get "/cart", to: 'cart#index'
  
  resources :orders, only: [:index, :show, :update], concerns: :commentable
  resources :order_lines, only: [:create, :destroy]
  resources :product, except: [:destroy, :create, :new], concerns: :commentable
  resources :profiles, concerns: :commentable
  resources :customers, only: [:index, :new, :create]
  resources :charges
end

app/models/product.rb
# frozen_string_literal: true

# Module of table products
class Product < ApplicationRecord
  has_many :order_lines
  has_many :orders, through: :order_lines
  has_many :product_prices_log
  has_many :product_tags
  has_many :tags, through: :product_tags
  has_many :likes
  has_many :comments, as: :commentable
  has_one_attached :picture

  validates :price, :stock, :description, :name, :sku, presence: true
  validates :sku, uniqueness: true
  validates :price, numericality: { greater_than_or_equal_to: 10 }
  validates :stock, numericality: { greater_than_or_equal_to: 1 }, on: :create
  validates :stock, numericality: { greater_than_or_equal_to: 0 }, on: :update

  scope :sclikes, -> { order(like_count: :DESC) }
  scope :scdislikes, -> { order(dislike_count: :DESC) }
  scope :scnames, -> { order(:name) }

  after_update :monitor_stock

  private

  def monitor_stock
    return unless stock < 4

    return unless previous_changes['stock'].present?

    MailerFromMonitorStock.perform_async(id) if like_count > 0
  end
end

app/controllers/admin/product_controller.rb
# frozen_string_literal: true
require 'product_edit_form.rb'
require 'admin/product_new_form.rb'
require 'products_filter.rb'
require 'securerandom'

class Admin::ProductController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy] 
  
  def index
    authorize [:admin, Product]
    @product = Product.all
    @tags = Tag.all
    @searcher = ProductFilter.new(params).call
    # if a filter has been used @searcher now contains a hash with a key call historic inside this key
    # there will be three more keys: tags, scope and search each one stores the value from the last filter applied 
    if @searcher[:historic]
      @product = filter_by_tags(@product, @searcher[:historic])
      @product = ProductQuery.new(@product).apply_scope(@searcher[:historic][:scope])
      @product = ProductQuery.new(@product).with_name_like(@searcher[:historic][:search])
    end
    @product = @product.paginate(page: params[:page], per_page: 6)
  end

  def show
    authorize [:admin, @product]
    @p = @product
    # it setups the variables needed to make a new comment
    setup_next_comment('Product', @product)
  end

  def new
    authorize [:admin, Product]
    @product = Product.new
    @tags = Tag.all
  end

  def create
    authorize [:admin, Product]
    @form = Admin::ProductCreateForm.new(product_params)
    @form.assign_attributes(sku: SecureRandom.uuid)
    if @form.save
      flash[:success] = "The product has been created successfully"
      redirect_to admin_product_index_path
    else
      flash[:error] = [@form.errors.messages]
      redirect_to new_admin_product_path
    end
  end
  
  def edit
    authorize [:admin, @product]
    @tags = Tag.all
  end
  
  def update
    authorize [:admin, @product]
    @form = ProductEditForm.new(product_params)
    @form.assign_attributes(id: @product.id, sku: @product.sku, admin: current_user.id)
    if @form.save
      flash[:success] = "Product updated"
      redirect_to admin_product_index_path
    else
      flash[:error] = ["There has been a problem updating the product. #{form.errors.messages}"]
      redirect_to edit_admin_product_path(product_params)
    end 
  end

  def destroy
    authorize [:admin, @product]
    if @product.update(active: false)
      flash[:success] = "The product has been deactivated"
    else
      flash[:error] = ["An error has ocurred the product couldn't be deactivated"]
    end
    redirect_to admin_product_index_path
  end

  private
  
  def set_product
    @product = ProductQuery.new.get(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :stock, :description, :picture, :tag_ids => [])
  end

  def filter_by_tags(products, historic)
    return products unless historic[:tags].present?
    
    products = ProductQuery.new(products).get_products_by_tags(historic[:tags])
  end

  def user_like(product)
    # search for the user's like, this is need because there is only like/dislike of user for each product
    Like.where('user_id = ? AND product_id = ?', current_user.id, product).first
  end
end

app/controllers/api/v1/products_controller.rb
module Api
  module V1
    class ProductsController < ApplicationController
      before_action :doorkeeper_authorize!, only: [:asign_like]
      def index
        @products = Product.all
        if params[:filter].present?
          @products = filter_by_tags(@products, params[:filter])
          @products = ProductQuery.new(@products).apply_scope(params[:filter][:scope])
          @products = ProductQuery.new(@products).with_name_like(params[:filter][:search])
        end
        @products = @products.paginate(page: params[:page], per_page: 6)
      end

      def asign_like
        record_like = Like.user_like(current_user.id, params[:product]).first
        # a user can only give one kind of like to each product 
        # if the other kind of like is selected the former will be removed
        if record_like.present?
          if record_like.kind == 'like' && params[:type] == 'dislike'
            record_like.update!(kind: 'dislike')
          elsif record_like.kind == 'dislike' && params[:type] == 'like'
            record_like.update!(kind: 'like')
          end
        else
          product = ProductQuery.new.get(params[:product])
          product.likes.create!(user_id: current_user.id, kind: params[:type])
        end
        head :no_content
      end

      private

      def filter_by_tags(products, historic)
        return products unless historic[:tags].present?
    
        products = ProductQuery.new(products).get_products_by_tags(historic[:tags])
      end
    end
  end
end

app/controllers/product_controller.rb
# frozen_string_literal: true
require 'product_edit_form'
require 'products_filter.rb'

# product controller
class ProductController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_product, only: [:show,:edit, :update] 

  def index
    @product = ProductQuery.new.active
    @tags = Tag.all
    @searcher = ProductFilter.new(params).call
    # if a filter has been used @searcher now contains a hash with a key call historic inside this key
    # there will be three more keys: tags, scope and search each one stores the value from the last filter applied 
    if @searcher[:historic]
      @product = filter_by_tags(@product, @searcher[:historic])
      @product = ProductQuery.new(@product).apply_scope(@searcher[:historic][:scope])
      @product = ProductQuery.new(@product).with_name_like(@searcher[:historic][:search])
    end
    @product = @product.paginate(page: params[:page], per_page: 6)
  end

  def show
    @p = @product
    # it setups the variables needed to make a new comment
    setup_next_comment('Product', @product)
  end

  def asign_like
    return unless current_user
    
    record_like = Like.user_like(current_user.id, params[:product]).first
    # a user can only give one kind of like to each product 
    # if the other kind of like is selected the former will be removed
    if record_like.present?
      if record_like.kind == 'like' && params[:type] == 'dislike'
        record_like.update!(kind: 'dislike')
      elsif record_like.kind == 'dislike' && params[:type] == 'like'
        record_like.update!(kind: 'like')
      end
    else
      product = ProductQuery.new.get(params[:product])
      product.likes.create!(user_id: current_user.id, kind: params[:type])
    end
    @p = ProductQuery.new.get(params[:product])
  end

  def edit
    authorize @product
    @tags = Tag.all
  end
  
  def update
    authorize @product
    @form = ProductEditForm.new(product_params)
    @form.assign_attributes(id: @product.id, price: @product.price, sku: @product.sku, admin: current_user.id)
    if @form.save
      flash[:success] = "Product updated"
      redirect_to product_index_path
    else
      flash[:error] = ["There has been a problem updating the product. #{@form.errors.messages}"]
      redirect_to edit_product_path(product_params)
    end
  end

  private

  def set_product
    @product = ProductQuery.new.get(params[:id])
  end
  
  def product_params
    params.require(:product).permit(:name, :stock, :description, :picture, :tag_ids => [])
  end

  def filter_by_tags(products, historic)
    return products unless historic[:tags].present?
    
    products = ProductQuery.new(products).get_products_by_tags(historic[:tags])
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/_form_buy.html.erb
<% if product.stock > 0 %>
  <%= form_for :order_line, :url => order_lines_path, method: :post do |f| %>
    <%= f.hidden_field :product_id, :value => product.id %>
    <% product.tags.each do |t| %>
      <span class="ui tag label">
        <%=label 'tag_name', t.name%>
      </span>
    <% end %><br>
    <div class="meta">
      Price: $<%=product.price%>
    </div>
    <div class="ui labeled small input">
      <div class="ui label">
        Quantity
      </div>
    <%= f.number_field :quantity, in: 1..product.stock %>
    </div>
    <%= f.submit "Add to Cart", :class => "ui small button" %>
  <% end %>
<% else %>
  <span>Out Of Stock</span>
<% end %>
<%if current_user&.admin == 1%>
  <%= link_to "Edit", edit_product_path(@p.id),  :class =>"ui toggle small button" %>
<%end%>
<% if user_signed_in? %>
  <div class="ui labeled button" tabindex="0">
    <div class="ui tiny button">
      <i class="thumbs up icon"></i><%= link_to "Like", like_path(product: product.id, type: "like"), remote: true %>
    </div>
    <a class="ui basic label">
      <%= product.like_count %>
    </a>
  </div>
  <div class="ui labeled button" tabindex="0">
    <div class="ui tiny button">
      <i class="thumbs down icon"></i><%= link_to "Dislike", like_path(product: product.id, type: "dislike"), remote: true %>
    </div>
    <a class="ui basic label">
      <%= product.dislike_count %>
    </a>
  </div>   
<% end %>

app/views/product/_product_form.html.erb
<%= f.label 'Name:' %>
<%= f.text_field :name %><br>

<%= f.label 'Sku:' %> <%= @product.sku%><br>

<%= f.label 'Description' %><br>
<%= f.text_area :description %><br>
  
<%= f.label 'Stock:' %>
<%= f.number_field :stock %><br>

<%= f.label 'Price:' %> <%= @product.price%><br>

<%= f.label 'Picture:' %>
<%= f.file_field :picture %><br>

<% @tags.each do |t| %>
  <%= f.label 'tag_name', t.name%>
  <%= f.check_box :tag_ids, { multiple: true }, t.id, false %>
<% end %><br>

app/views/product/_product_list.html.erb
<% counter = 0%>
<div class="ui two column grid">
  <% @product.each do |product| %>
    <% @p = product %>
    <% if counter == 0 %>
      <div  class="row">
    <%end%> 
    <div class="column">
      <div class="ui divided items">
        <div class="item">
          <div class="ui small image">
            <%unless product.picture.attached?%>
              <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg">
            <%else%>
              <img src="<%= product.picture.variant(resize: "220x220!").service_url%>">
            <%end%>
          </div>
          <div class="middle aligned content">
            <%= link_to product_path(@p.id) do %>
              <h2><%= truncate(@p.name, length: 35) %></h2>
            <%end%>
            <div id = <%="likes"+@p.id.to_s%>>
              <%= render partial: "form_buy", locals: {product: @p}%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if counter == 1 %>
      </div>
    <%end%>
    <%counter += 1%>
    <% counter = 0 unless counter < 2 %>
  <% end %>
</div>
<%= will_paginate @users, :params => { filter: {
                                                search: (params[:filter][:search] rescue nil),
                                                scope: (params[:filter][:scope] rescue nil),
                                                tag: nil,
                                                historic: (@searcher[:historic] rescue nil) } } %>

app/views/product/_scopes_list.html.erb
<%=link_to 'Name', product_index_path( { filter: {
                                                scope: 'names',
                                                historic: (@searcher[:historic] rescue nil) } }
                                      ), remote: true, :class=>'ui button' %>
<%=link_to 'Likes', product_index_path( { filter: {
                                                scope: 'likes',
                                                historic: (@searcher[:historic] rescue nil) } }
                                      ), remote: true, :class=>'ui button' %>
<%=link_to 'Dislikes', product_index_path( { filter: {
                                                  scope: 'dislikes',
                                                  historic: (@searcher[:historic] rescue nil) } }
                                          ), remote: true, :class=>'ui button' %>

app/views/product/_tags_list.html.erb
<% @tags.each do |t| %>
    <%= link_to t.name, product_index_path({ filter: { 
                                              historic: (@searcher[:historic] rescue nil),
                                              tag: t.id
                                             } }), remote: true, :class=>"ui tag label", :id=>"t#{t.id}"  %> 
<%end%>

app/views/product/asign_like.js.erb
(function init() {
  let el = document.querySelector('<%="#likes"+@p.id.to_s%>')

  el.innerHTML = '<%= escape_javascript(render partial: "form_buy", locals: {product: @p}) %>';
})()

app/views/product/edit.html.erb
<%= form_for @product, html: { autocomplete: "off" } do |f| %>
  <%= render partial: "product_form", locals: {f: f}%>
  <%= f.submit 'Update Product' %>
<% end %>


<%= link_to "regresar", product_index_path %>

app/views/product/index.html.erb
<div class="ui icon input">
  <%= form_for :filter, method: :get, remote: true  do |f|%>
    <%= f.hidden_field :historic, :value => (@searcher[:historic] rescue nil) %>
    <div class="ui input">
      <%= f.text_field :search, :placeholder=>"Search..." %>
    </div>
    <%= f.submit "Search", :class => "ui icon button" %>
    <%= link_to product_index_path, remote: true, :class=>'ui icon button' do%>
      <i class="eraser icon"></i>
    <%end%>
  <%end%>
  <div id='scopes' class="ui right buttons">
    <%= render partial: "scopes_list" %>
  </div>
</div>
<br><br>
<div id='tags' >
  <%= render partial: "tags_list" %>
</div>
<br>
<div id='list'>
  <%= render partial: "product_list"%>
</div>
<%= render "shared/link_back" %>

app/views/product/index.js.erb
(function init() {
  let el = document.querySelector('#list')
  let al = document.querySelector('#tags')
  let ol = document.querySelector('#scopes')
  
  ol.innerHTML = '<%= escape_javascript(render(partial: "scopes_list")) %>';
  al.innerHTML = '<%= escape_javascript(render(partial: "tags_list")) %>';
  el.innerHTML = '<%= escape_javascript(render(partial: "product_list")) %>';
  <% if @searcher[:historic].present? && @searcher[:historic][:tags].present? %>
    <% @searcher[:historic][:tags].each do |t| %>
      $('<%= escape_javascript("#t#{t.to_s}") %>').addClass('green');
    <% end %>
  <% end %>
})()

app/views/product/show.html.erb
<div>
  <p>Name: <%= @product.name %></p>
  <p>Sku: <%= @product.sku %></p>
  <p>Description: <%= truncate(@p.description, length: 50)%></p>
  <p>Price: $<%= @product.price %></p>
  <p>Stock:
  <% if @product.stock == 0 %>
    Out of Stock
  <% else %>
    <%= @product.stock%>
  <% end %>  
  </p>
  <div id= <%= "likes"+@product.id.to_s %> >
    <%= render partial: "form_buy", locals: {product: @product}%>
  </div>
</div>
<div>
  <%= render partial: "shared/new_comment", locals: {comment: @comment, commentable: @commentable, type: @type, current_user: current_user, comments: @comments } %>
</div>

<%= render "shared/link_back" %>